import React from "react";
import "./index.css";

const About = () => {
  return (
    <div className="container">
      <ul>
        <li>
          <h1>Aboutfirst</h1>
        </li>
        <li>
          <h1>About</h1>
        </li>
        <li>
          <h1>About</h1>
        </li>
        <li>
          <h1>About</h1>
        </li>
        <li>
          <h1>About</h1>
        </li>
        <li>
          <h1>About</h1>
        </li>
        <li>
          <h1>About</h1>
        </li>
        <li>
          <h1>About</h1>
        </li>
        <li>
          <h1>About</h1>
        </li>
        <li>
          <h1>About</h1>
        </li>
        <li>
          <h1>About</h1>
        </li>
        <li>
          <h1>About</h1>
        </li>
        <li>
          <h1>About</h1>
        </li>
        <li>
          <h1>About</h1>
        </li>
        <li>
          <h1>About</h1>
        </li>
        <li>
          <h1>About</h1>
        </li>
        <li>
          <h1>About</h1>
        </li>
        <li>
          <h1>About</h1>
        </li>
        <li>
          <h1>About</h1>
        </li>
        <li>
          <h1>About</h1>
        </li>
        <li>
          <h1>About</h1>
        </li>
        <li>
          <h1>About</h1>
        </li>
        <li>
          <h1>About</h1>
        </li>
        <li>
          <h1>About</h1>
        </li>
        <li>
          <h1>About</h1>
        </li>
        <li>
          <h1>About</h1>
        </li>
        <li>
          <h1>Aboutlast</h1>
        </li>
      </ul>
    </div>
  );
};

export default About;
